---
 - name: jenkins setup
   hosts: all
   become: yes
   tasks:
    - name: "jenkins yum repository"
      yum_repository:
        name: jenkins
        description: "jenkins YUM repo"
        baseurl: "http://pkg.jenkins-ci.org/redhat-stable/"
    - name: "jenkins-ci.org.key installed"
      rpm_key:
        key: "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"
    - name: "Jenkins installed"
      yum:
        name: jenkins
    - name: "Jenkins service started"
      service:
        name: jenkins
        state: started
        enabled: yes 
